version: "3"

dotenv: [".env"]

vars:
  DC: docker compose -f .setup/compose.yml --env-file .env
  BACKEND_PORT: "6400"
  FRONTEND_PORT: "5173"
  CHATDEV_REPO: "https://github.com/OpenBMB/ChatDev.git"
  SRC_DIR: ".src"

tasks:
  default:
    desc: Show available tasks
    silent: true
    cmds:
      - task --list

  update:
    desc: Update Claude CLI
    cmds:
      - claude update
      - claude --version
    silent: true

  claude:
    desc: Run Claude with specific flags
    deps:
      - update
    vars:
      ARGS: --chrome --ide --model opus
    cmds:
      - claude {{.ARGS}} --continue 2>/dev/null || claude {{.ARGS}}
    silent: true

  dangerous:
    desc: Run Claude dangerously...
    deps:
      - update
    cmds:
      - claude --allow-dangerously-skip-permissions --chrome --ide --model opus --continue
    silent: true

  # ===== Source Management =====
  clone:
    desc: Clone ChatDev repo into .src/ (skips if already present)
    cmds:
      - git clone {{.CHATDEV_REPO}} {{.SRC_DIR}}
    status:
      - test -d {{.SRC_DIR}}/.git

  reclone:
    desc: Delete .src/ and re-clone ChatDev from scratch
    cmds:
      - rm -rf {{.SRC_DIR}}
      - task: clone

  # ===== Docker Compose =====
  up:
    desc: Build and start all services
    deps: [clone]
    cmds:
      - "{{.DC}} up --build -d"
      - echo "Waiting for services to become healthy..."
      - task: clean-workflows
      - echo ""
      - echo "Backend   → http://localhost:{{.BACKEND_PORT}}"
      - echo "Frontend  → http://localhost:{{.FRONTEND_PORT}}"
      - echo "LLM       → $BASE_URL"

  down:
    desc: Stop and remove containers
    cmd: "{{.DC}} down"

  restart:
    desc: Stop, re-clone ChatDev source, rebuild and start
    cmds:
      - "{{.DC}} down"
      - task: reclone
      - task: up

  logs:
    desc: Tail logs from all services
    cmd: "{{.DC}} logs -f"

  logs:backend:
    desc: Tail backend logs only
    cmd: "{{.DC}} logs -f backend"

  ps:
    desc: Show running services
    cmd: "{{.DC}} ps"

  shell:
    desc: Open a shell in the backend container
    cmd: "{{.DC}} exec backend bash"

  # ===== Workflow Cleanup =====
  clean-workflows:
    desc: Remove all sample workflows shipped with ChatDev
    cmds:
      - |
        python3 -c "
        import json, urllib.request

        BASE = 'http://localhost:{{.BACKEND_PORT}}'
        with urllib.request.urlopen(f'{BASE}/api/workflows') as r:
            workflows = json.loads(r.read()).get('workflows', [])
        deleted = 0
        for wf in workflows:
            req = urllib.request.Request(f'{BASE}/api/workflows/{wf}', method='DELETE')
            try:
                urllib.request.urlopen(req)
                deleted += 1
            except Exception as e:
                print(f'  ✗ {wf}: {e}')
        print(f'Cleaned {deleted} sample workflow(s).')
        "

  # ===== Maintenance =====
  purge:
    desc: Forcefully delete all .gitignored paths (.data/, .setup/, .src/, etc.)
    prompt: This will delete ALL gitignored files and directories. Continue?
    cmd: git clean -ffdX -e .setup/

  validate:
    desc: Validate all YAML workflow files
    cmd: "{{.DC}} exec backend python tools/validate_all_yamls.py"

  sync:
    desc: Sync Vue graphs to database
    cmd: "{{.DC}} exec backend python tools/sync_vuegraphs.py"

  clean:
    desc: Stop containers and remove volumes in .data/
    prompt: This will delete all data (WareHouse, logs). Continue?
    cmds:
      - "{{.DC}} down"
      - rm -rf .data/warehouse/* .data/logs/* .data/data/*

  # ===== Setup =====
  setup:
    desc: First-time setup — create .env from template
    deps: [purge]
    cmds:
      - test -f .env || cp .setup/.env.example .env
      - echo "Created .env — edit it to configure your LLM provider, then run 'task up'"
